# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LocalServer
                                 A QGIS plugin
 This plugin is an integration of the Infra3D application with QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-09-28
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Sourcepole AG
        email                : hka@sourcepole.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import json
import mimetypes
import threading
from collections import deque
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

from qgis.PyQt.QtCore import QObject, pyqtSignal
from qgis.PyQt.QtNetwork import QHostAddress

try:
    from PyQt5.QtWebSockets import QWebSocketServer
    NON_SECURE_MODE = QWebSocketServer.NonSecureMode
except ImportError:
    from PyQt6.QtWebSockets import QWebSocketServer
    NON_SECURE_MODE = QWebSocketServer.SslMode.NonSecureMode


class LocalServer(QObject):
    websocket_message_received = pyqtSignal(dict)

    def __init__(self):
        super().__init__()
        self.root_dir = Path(__file__).resolve().parent
        self.static_dir = self.root_dir / "static"
        self.running = False
        self.http_server = None
        self.started = threading.Event()
        self.startup_error = None
        self._websocket_queue = deque()
        self._websocket_server = None
        self._websocket_clients = set()
        self._websocket_port = None

    def index(self) -> str:
        return (
            (self.static_dir / "index.html")
            .read_text(encoding="utf-8")
            .replace("__INFRA3D_WEBSOCKET_URL__", self.websocket_address())
        )

    def start_websocket(self, port: int = 0) -> bool:
        if self._websocket_server is not None:
            return True

        self._websocket_server = QWebSocketServer(
            "Infra3dLocalServer",
            NON_SECURE_MODE,
        )

        if not self._websocket_server.listen(QHostAddress("127.0.0.1"), port):
            self._websocket_server = None
            self.startup_error = True
            return False

        self._websocket_port = int(self._websocket_server.serverPort())
        self._websocket_server.newConnection.connect(self._on_new_websocket_connection)
        return True

    def websocket_address(self) -> str:
        if self._websocket_port is None:
            return ""
        return f"ws://127.0.0.1:{self._websocket_port}"

    def send_websocket_message(self, payload: dict):
        message = json.dumps(payload)
        if not self._websocket_clients:
            self._websocket_queue.append(message)
            return

        for socket in list(self._websocket_clients):
            if socket is None:
                continue
            socket.sendTextMessage(message)

    def _on_new_websocket_connection(self):
        if self._websocket_server is None:
            return

        socket = self._websocket_server.nextPendingConnection()
        if socket is None:
            return

        self._websocket_clients.add(socket)
        socket.textMessageReceived.connect(
            lambda message, ws=socket: self._handle_websocket_message(ws, message)
        )
        socket.disconnected.connect(lambda ws=socket: self._handle_websocket_closed(ws))

        while self._websocket_queue:
            socket.sendTextMessage(self._websocket_queue.popleft())

    def _handle_websocket_message(self, socket, message: str):
        try:
            payload = json.loads(message)
        except json.JSONDecodeError:
            return

        self.websocket_message_received.emit(payload)

    def _handle_websocket_closed(self, socket):
        self._websocket_clients.discard(socket)
        socket.deleteLater()

    def _close_websocket(self):
        if self._websocket_server is None:
            self._websocket_clients.clear()
            self._websocket_queue.clear()
            self._websocket_port = None
            return

        for socket in list(self._websocket_clients):
            socket.close()
            socket.deleteLater()

        self._websocket_clients.clear()
        self._websocket_queue.clear()
        self._websocket_server.close()
        self._websocket_server.deleteLater()
        self._websocket_server = None
        self._websocket_port = None

    

    def _build_handler(self):
        server = self

        class Infra3dRequestHandler(BaseHTTPRequestHandler):
            server_version = "Infra3dLocalServer/1.0"

            def log_message(self, format, *args):
                return

            def do_GET(self):
                parsed_url = urlparse(self.path)
                if parsed_url.path in ("/", "/index.html"):
                    self._send_text(server.index(), "text/html; charset=utf-8")
                    return

                if parsed_url.path.startswith("/static/"):
                    self._serve_static(parsed_url.path[8:])
                    return

                if parsed_url.path == "/api/ping":
                    self._send_json({"status": "ok"})
                    return

                self.send_error(HTTPStatus.NOT_FOUND)

            def do_POST(self):
                parsed_url = urlparse(self.path)
                payload = self._read_json_body()
                # No POST endpoints for polling remain. Only static assets and page serving.

                self.send_error(HTTPStatus.NOT_FOUND)

            def _read_json_body(self):
                content_length = int(self.headers.get("Content-Length", "0"))
                if content_length <= 0:
                    return {}
                raw_body = self.rfile.read(content_length)
                if not raw_body:
                    return {}
                return json.loads(raw_body.decode("utf-8"))

            def _serve_static(self, relative_path: str):
                target = (server.static_dir / relative_path).resolve()
                static_root = server.static_dir.resolve()
                if static_root not in target.parents and target != static_root:
                    self.send_error(HTTPStatus.NOT_FOUND)
                    return
                if not target.is_file():
                    self.send_error(HTTPStatus.NOT_FOUND)
                    return

                content_type = mimetypes.guess_type(str(target))[0] or "application/octet-stream"
                self._send_bytes(target.read_bytes(), content_type)

            def _send_json(self, payload):
                self._send_bytes(json.dumps(payload).encode("utf-8"), "application/json; charset=utf-8")

            def _send_text(self, payload: str, content_type: str):
                self._send_bytes(payload.encode("utf-8"), content_type)

            def _send_bytes(self, payload: bytes, content_type: str):
                self.send_response(HTTPStatus.OK)
                self.send_header("Content-Type", content_type)
                self.send_header("Content-Length", str(len(payload)))
                self.send_header("Cache-Control", "no-store")
                self.end_headers()
                self.wfile.write(payload)

        return Infra3dRequestHandler

    def start(self, port: int = 5000, debug: bool = False):
        self.running = True
        self.started.clear()
        self.startup_error = None
        handler = self._build_handler()

        class ReusableThreadingHTTPServer(ThreadingHTTPServer):
            allow_reuse_address = True

        try:
            self.http_server = ReusableThreadingHTTPServer(("127.0.0.1", port), handler)
            self.started.set()
        except Exception:
            self.startup_error = True
            self.running = False
            self.started.set()
            raise

        try:
            self.http_server.serve_forever(poll_interval=0.25)
        finally:
            self.running = False
            self.started.set()

    def stop(self):
        self._close_websocket()

        if self.http_server is None:
            self.running = False
            self.started.clear()
            return

        self.http_server.shutdown()
        self.http_server.server_close()
        self.http_server = None
        self.running = False
        self.started.clear()


if __name__ == "__main__":
    server = LocalServer()
    server.start()