# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Infra3d
                                 A QGIS plugin
 This plugin is an integration of the Infra3D application with QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-09-28
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Sourcepole AG
        email                : hka@sourcepole.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from threading import Thread
from typing import Callable
import os.path
import sys
from pyproj import Transformer
import json

# Add prepackaged dependencies to PYTHONPATH so the plugin can use them
sys.path.append(os.path.join(os.path.dirname(__file__), "dependencies/site-packages"))

from qgis.gui import QgisInterface, QgsMapToolPan
from qgis.core import Qgis, QgsPointXY, QgsRectangle, QgsDataSourceUri, QgsProject, QgsVectorLayer, QgsCoordinateReferenceSystem, QgsJsonUtils
from qgis.PyQt.QtCore import QEventLoop, QSettings, QTranslator, QCoreApplication, QUrl, Qt
from qgis.PyQt.QtGui import QIcon, QDesktopServices, QGuiApplication
from qgis.PyQt.QtWidgets import QAction

from .infra3d_settings import Infra3DSettings, DEFAULT_SERVER_PORT, DEFAULT_PG_SERVER_PORT, str2bool
from .infra3d_client import Infra3dClient
from .infra3d_map_tool import Infra3dMapTool
from .server.socketio_server import SocketIOServer
from .marker_map_item import MarkerMapItem

from .resources import *


class Infra3d:
    """QGIS Plugin Implementation."""

    def __init__(self, iface: QgisInterface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value("locale/userLocale", "en")[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            "i18n",
            "Infra3d_{}.qm".format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.toolbar = self.iface.addToolBar("infra3D")
        self.toolbar.setObjectName("infra3D")
        self.settings = QSettings()
        self.settings_dialog = Infra3DSettings(self.iface.mainWindow())

        # Start socketio server
        self.socketio_server = SocketIOServer()
        self.start_socketio_server(self.settings.value("/infra3d_viewer/server_port",  DEFAULT_SERVER_PORT))

        # Initialize Infra3D client
        self.infra3d_client = Infra3dClient(self.socketio_server_address())

        # Initialize marker object that will be used to show the tracked position
        self.infra3d_marker = MarkerMapItem(self.iface.mapCanvas())
        self.infra3d_marker.hide()

        # Initialize map tool
        self.infra3d_map_tool = Infra3dMapTool(
            self.iface,
            self.infra3d_client,
            self.infra3d_marker,
            self.start_infra3d_blocking
        )
        
        self.panTool = QgsMapToolPan(self.iface.mapCanvas())
        self.point_transformer = Transformer.from_crs("EPSG:4326", "EPSG:3857", always_xy=True)
        
        # network
        self.network_layer = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message: str) -> str:
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate("infra3D", message)

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        # Ownership of a QAction is not transfered to QMenu, so we need to keep
        # the references of the actions alive. The easiest way is with an actions list.
        
        self.start_infra3d_action = QAction(QIcon(":/plugins/infra3d_viewer/infra3d.png"), self.tr("Enable infra3D"))
        self.start_infra3d_action.toggled.connect(self.start_infra3d)
        self.start_infra3d_action.setCheckable(True)
        self.actions.append(self.start_infra3d_action)
        
        set_infra3d_position_action = QAction( QIcon(":/plugins/infra3d_viewer/infra3d_marker.png"), self.tr("Set infra3D position"), self.iface.mainWindow())
        set_infra3d_position_action.triggered.connect(self.set_infra3d_position)
        set_infra3d_position_action.setCheckable(True)
        self.infra3d_map_tool.setAction(set_infra3d_position_action)
        self.actions.append(set_infra3d_position_action)

        zoom_to_marker = QAction(QIcon(":/plugins/infra3d_viewer/infra3d_zoom.png"), self.tr("Zoom to marker"), self.iface.mainWindow())
        zoom_to_marker.triggered.connect(self.zoom_to_marker)
        self.actions.append(zoom_to_marker)

        # TODO: remove settings or make layers selectable
        # self.infra3d_settings = Infra3DSettings(self.iface.mainWindow())
        # self.show_settings_action = QAction(QIcon(":/images/themes/default/mActionOptions.svg"), self.tr("Settings"))
        # self.show_settings_action.triggered.connect(self.infra3d_settings.show)
        # self.show_settings_action.setCheckable(False)
        # self.actions.append(self.show_settings_action)
        
        # synchronizing network
        self.iface.mapCanvas().extentsChanged.connect(self.onExtentsChanged)

        for action in self.actions:
            self.toolbar.addAction(action)

    def set_projection(self) -> None:
        """
        Set the projection to EPSG:3857
        """
        target_crs = QgsCoordinateReferenceSystem("EPSG:3857") # LV95
        project = QgsProject.instance() # get current project
        project.setCrs(target_crs) # update projection
        self.iface.mapCanvas().refresh()
    
    def onExtentsChanged(self) -> None:
        """
        Fired whenever the extent of the QGIS mapCanvas changes.
        """
        try:
            extent = self.iface.mapCanvas().extent().toString()
            scale = self.iface.mapCanvas().scale()
            ll, ur = extent.split(" : ")
            eMin, nMin = [float(i) for i in ll.split(",")]
            eMax, nMax = [float(i) for i in ur.split(",")]
            self.infra3d_client.getNetwork(scale, eMin, eMax, nMin, nMax)
        except Exception as e:
            print(e)    
            
    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        for action in self.actions:
            self.iface.removePluginWebMenu(
                self.tr("infra3D"),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    def start_infra3d(self, checked: bool):
        """
        Starts/ends the webserver.

        Parameters
        ----------
        checked : bool
            enable/disable
        """
        self.set_projection()
        if checked:
            self.open_browser_and_connect(
                lambda: (
                    QGuiApplication.restoreOverrideCursor(),
                    self.infra3d_client.setOnPositionChanged()
                )
            )
            # Listen on tracking signal
            self.infra3d_client.position_changed.connect(
                lambda response: self.place_marker(
                    QgsPointXY(*self.point_transformer.transform(response["easting"], response["northing"])),
                    response["orientation"]
                )
            )
        else:
            self.iface.mapCanvas().setMapTool(self.panTool)
            self.infra3d_client.unsetOnPositionChanged()
            try:
                self.infra3d_client.position_changed.disconnect()
            except TypeError:
                # When the signal is not connected and we call disconnect()
                # then we get
                # TypeError: disconnect() failed between 'position_changed' and all its connections
                # That's why we just ignore it
                pass
            self.infra3d_marker.hide()

    def start_infra3d_blocking(self):
        """
        Blocks infra3d
        """
        if not self.start_infra3d_action.isChecked():
            # Wait until started
            QGuiApplication.setOverrideCursor(Qt.CursorShape.WaitCursor)
            blockingWait = QEventLoop()
            self.infra3d_client.webapp_initialized.connect(blockingWait.quit)
            self.infra3d_client.connection_failed.connect(blockingWait.quit)
            self.start_infra3d_action.toggle()
            blockingWait.exec_()
            QGuiApplication.restoreOverrideCursor()

    def set_infra3d_position(self, checked: bool):
        """
        Update the projection of the QGIS mapCanvas and enable/disable the position picker to define the position the viewer is supposed to jump to.

        Parameters
        ----------
        checked : bool
            Enable/disable
        """
        self.set_projection()
        if checked:
            if str2bool(self.settings.value("/infra3d_viewer/load_pg_layer", 'false')):
                self.add_infra3d_layers()
            self.iface.mapCanvas().setMapTool(self.infra3d_map_tool)
        else:
            self.iface.mapCanvas().setMapTool(self.panTool)

    def check_settings(self) -> bool:
        """Check whether the settings are configured propertly.

        Returns:
            bool: Return True if the settings are defined,
            otherwise returns False
        """
        # TODO: remove settings or make layers selectable

        missing_configurations = []
        # NOTE: Don't need that anymore
        # if not self.settings.value("/infra3d_viewer/infra3d_username"):
        #     missing_configurations.append("Infra3d username")
        # if not self.settings.value("/infra3d_viewer/infra3d_password"):
        #     missing_configurations.append("Infra3d password")

        # NOTE: bool('false') --> True --- boolean operator on a string only returns false if string is empty
        # NOTE: Therefore, we must compare the content with 'true'
        if str2bool(self.settings.value('/infra3d_viewer/load_pg_layer', 'false')):
            if not self.settings.value("/infra3d_viewer/database/host"):
                missing_configurations.append("DB host")
            if not self.settings.value("/infra3d_viewer/database/database"):
                missing_configurations.append("DB name")
            if not self.settings.value("/infra3d_viewer/database/tablename"):
                missing_configurations.append("Table name")
            if not self.settings.value("/infra3d_viewer/database/schema"):
                missing_configurations.append("Schema name")
            if not self.settings.value("/infra3d_viewer/database/geometry_column"):
                missing_configurations.append("Geometry column")
        if len(missing_configurations) > 0:
            self.iface.messageBar().pushMessage(
                "infra3DRoad",
                self.tr(
                    "The following settings are not set: " + ", ".join(missing_configurations)
                ),
                Qgis.MessageLevel.Critical,  # type: ignore
                5
            )
            return False

        return True

    def open_browser_and_connect(self, callback_after_init: Callable):
        """Start / open a browser / browser tab and initialize the
        Infra3D application via the `init` function.
        See: https://www.infra3d.ch/latest/api/apidoc/Reference/

        Args:
            callback_after_init (Callable): Callback that should be executed
            after the Infra3D application has been initialized. See
            `Infra3dClient.webapp_initialized` for more information about the
            initialization phase.
        """

        # Don't do anything if the socketio server is not running
        if self.socketio_server.running is False:
            QGuiApplication.restoreOverrideCursor()
            self.iface.messageBar().pushMessage(
                "infra3D",
                self.tr("infra3D server did not start correctly. Please restart QGIS"),
                Qgis.MessageLevel.Critical,  # type: ignore
                5
            )
            return

        # Check if settings are set correctly #TODO: remove settings or make layers selectable
        if self.check_settings() is False:
            QGuiApplication.restoreOverrideCursor()
            self.start_infra3d_action.setChecked(False)
            return

        # If we cannot connect to the server, then there is
        # no need to start the browser
        if not self.infra3d_client.connect():
            QGuiApplication.restoreOverrideCursor()
            return

        # Start browser
        QDesktopServices.openUrl(
            QUrl(
                self.socketio_server_address()
            )
        )

        # The web app needs to be loaded in the browser before we can
        # initialize the Infra3D application. The `webapp_loaded`
        # signal is emitted when a browser has been launched and
        # our JS code (code under server/static/js) was execeted.
        self.infra3d_client.webapp_loaded.connect(
            lambda: self.infra3d_client.init(
                self.settings.value("/infra3d_viewer/infra3d_username"),
                self.settings.value("/infra3d_viewer/infra3d_password")
            )
        )
        self.infra3d_client.network_changed.connect(
            lambda: self.on_network_changed()
        )
        self.infra3d_client.network_received.connect(
            lambda network: self.show_network(network)
        )
        # All Infra3D functions can only be called after the Infra3D application
        # has been loaded(see `Infra3D.webapp_loaded` signal) and initialized.
        # The `webapp_initialized` signal is emitted when this is the case.
        # Only now can we call Infra3D functions or listen to Infra3D events.
        self.infra3d_client.webapp_initialized.connect(callback_after_init)

    def on_network_changed(self) -> None:
        """Update the map canvas zoom level to 1000 and zoom to the current marker position.

        This function is called when the campaign is updated in Infra3D.
        """
        self.iface.mapCanvas().zoomScale(1000)
        self.zoom_to_marker()
        
        
    def show_network(self, network: json) -> None:
        routes = network.get("routes")
        if not routes or not routes.get("features"):
            print("Error: Network does not contain valid features!")
            return
        geom_type = routes["features"][0]["geometry"]["type"]
        
        #mapping for styles
        style_file = "infra3DRoad.qml" if geom_type.lower() == "linestring" else "infra3DHex.qml"
        style_path = os.path.join(self.plugin_dir, style_file)
        self._update_network_layer(routes, geom_type, style_path)
        
    def _update_network_layer(self, geojson_data: dict, geom_type: str, style_path: str) -> None:
        layer_name = "Befahrungsnetz infra3D"
        
        # remove layer if exists
        existing_layers = QgsProject.instance().mapLayersByName(layer_name)
        if existing_layers:
            QgsProject.instance().removeMapLayers([l.id() for l in existing_layers])
        
        # new mem layer
        layer = QgsVectorLayer(f"{geom_type}?crs=EPSG:4326", layer_name, "memory")
    
        if not layer.isValid():
            print("Fehler beim Erstellen des Layers")
            return
        
        # fill layer with features
        features = QgsJsonUtils.stringToFeatureList(json.dumps(geojson_data))
        if features:
            provider = layer.dataProvider()
            success, _ = provider.addFeatures(list(features))
        
            #styling
            if os.path.exists(style_path):
                layer.loadNamedStyle(style_path)
            
            #add layer to project
            QgsProject.instance().addMapLayer(layer)
            layer.triggerRepaint()
            
            if not success:
                print("Fehler beim Hinzufügen der Features")
            
        
    def place_marker(self, point: QgsPointXY, orientation: float):
        """Place the marker `self.infra3d_marker` on the map canvas and
        set the orientation.

        Args:
            point (QgsPointXY): QgsPointXY object to use when placing the marker
            orientation (float): Marker orientation
        """
        if self.infra3d_marker.isVisible() is False:
            self.infra3d_marker.show()
        self.infra3d_marker.setRotation(int(orientation))
        self.infra3d_marker.setMapPosition(point)

    def zoom_to_marker(self):
        """Zoom to the current position of the marker on the map
        and refresh the map canvas
        """
        if not self.infra3d_marker.isVisible():
            return

        
        self.set_projection()
        self.iface.mapCanvas().setExtent(
            QgsRectangle(
                self.infra3d_marker.current_position,
                self.infra3d_marker.current_position
            )
        )
        self.iface.mapCanvas().refresh()

    def start_socketio_server(self, port: int):
        """Start the socketio server in a different thread
        so we don't block the QGIS application.

        Args:
            port (int): Port on which the server should bind itself to
        """
        def start_server():
            self.socketio_server.start(port)

        thread = Thread(target=start_server)
        thread.start()

    def socketio_server_address(self) -> str:
        """Build the socketio server address

        Returns:
            str: Server address
        """
        return f"http://127.0.0.1:{self.settings.value('/infra3d_viewer/server_port', DEFAULT_SERVER_PORT)}"

    def add_infra3d_layers(self):
        """Add infra3d layers
        """
        # TODO: remove settings or make layers selectable
        uri = QgsDataSourceUri()

        uri.setConnection(
            self.settings.value("/infra3d_viewer/database/host"),
            str(self.settings.value("/infra3d_viewer/database/port", DEFAULT_PG_SERVER_PORT)),
            self.settings.value("/infra3d_viewer/database/database"),
            self.settings.value("/infra3d_viewer/database/username", ""),
            self.settings.value("/infra3d_viewer/database/password", "")
        )

        # Add Infra3D layer
        if len(QgsProject.instance().mapLayersByName("infra3DRoad")) == 0:
            uri.setDataSource(
                self.settings.value("/infra3d_viewer/database/schema"),
                self.settings.value("/infra3d_viewer/database/tablename"),
                self.settings.value("/infra3d_viewer/database/geometry_column")
            )

            layer = QgsVectorLayer(uri.uri(), "infra3DRoad", "postgres")
            if not layer.isValid():
                self.iface.messageBar().pushMessage(
                    "infra3D",
                    self.tr(
                        "Could not load infra3D layer"
                    ),
                    Qgis.MessageLevel.Warning,  # type: ignore
                    5
                )
            else:
                qmlFile = os.path.join(os.path.split(__file__)[0], 'infra3DRoad.qml')
                layer.loadNamedStyle( qmlFile, False )
                QgsProject.instance().addMapLayer(layer)
