# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Infra3DSettings
                                 A QGIS plugin
 This plugin is an integration of the Infra3D application with QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-09-28
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Sourcepole AG
        email                : hka@sourcepole.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from .infra3d_settings_loarule import LoaRule, LoaRuleTableModel
from qgis.core import Qgis, QgsApplication
from qgis.PyQt import uic
from qgis.PyQt.QtWidgets import QMainWindow, QDialog, QDialogButtonBox, QMessageBox
from qgis.PyQt.QtCore import QSettings, QModelIndex, Qt, QSortFilterProxyModel

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "ui/settings.ui")
)


DEFAULT_SERVER_PORT = 5000
DEFAULT_LAYER_GROUP = "infra3D"
DEFAULT_LOA_RULES = [
    {"type": "routes", "level": 0, "min": 0, "max": 1000},
    {"type": "routeLines", "level": 0, "min": 1000, "max": 4000},
    {"type": "routeLines", "level": 1, "min": 4000, "max": 70000},
    {"type": "routeHexes", "level": 0, "min": 70000, "max": 250000},
    {"type": "routeHexes", "level": 1, "min": 250000, "max": 1000000},
    {"type": "routeHexes", "level": 2, "min": 1000000, "max": float("inf")},
]


class Infra3DSettings(QDialog, FORM_CLASS):
    def __init__(self, parent: QMainWindow, iface):
        super(Infra3DSettings, self).__init__(parent)

        self.default_current_position_layer = self.tr("Current Position")
        self.default_network_layer_lines = self.tr("Network - Lines")
        self.default_network_layer_hexes = self.tr("Network - Hexes")

        self.setupUi(self)
        self.settings = QSettings()
        self.iface = iface

        # Get values from settings and prefill dialog
        self.prefill_from_settings()

        self.loaModel = LoaRuleTableModel(self.loaRules, self)
        self.tableView_loaRules.setModel(self.loaModel)

        self.loaProxyModel = QSortFilterProxyModel(self)
        self.loaProxyModel.setSourceModel(self.loaModel)

        # IMPORTANT: enable correct numeric sorting
        self.loaProxyModel.setSortRole(Qt.ItemDataRole.DisplayRole)
        self.loaProxyModel.setDynamicSortFilter(True)

        self.tableView_loaRules.setModel(self.loaProxyModel)
        self.tableView_loaRules.setSortingEnabled(True)

        # Set default sorting to ascending by min scale
        self.tableView_loaRules.sortByColumn(2, Qt.SortOrder.AscendingOrder)

        self.pushButton_addLoaRule.setIcon(
            QgsApplication.getThemeIcon("symbologyAdd.svg")
        )
        self.pushButton_removeLoaRule.setIcon(
            QgsApplication.getThemeIcon("symbologyRemove.svg")
        )
        self.pushButton_addLoaRule.clicked.connect(self.add_loa_rule)
        self.pushButton_removeLoaRule.clicked.connect(self.remove_loa_rule)

        self.pushButton_resetPage.clicked.connect(self.reset_page)
        self.buttonBox.button(QDialogButtonBox.StandardButton.Save).clicked.connect(
            self.save_settings
        )
        self.buttonBox.button(QDialogButtonBox.StandardButton.Cancel).clicked.connect(
            self.prefill_from_settings
        )

    def prefill_from_settings(self):
        """Fill lineedits in the settings dialog with values from QSettings or
        just use default values
        """
        # Infra3D credentials
        self.lineEdit_tenantIdentifier.setText(
            self.settings.value("/infra3d_viewer/general/tenant_identifier")
        )
        self.lineEdit_startProjectUID.setText(
            self.settings.value("/infra3d_viewer/general/start_project_uid")
        )
        # SocketIO server
        self.spinBox_serverPort.setValue(
            int(
                self.settings.value(
                    "/infra3d_viewer/general/server_port", DEFAULT_SERVER_PORT
                )
            )
        )

        self.lineEdit_layerGroup.setText(
            self.settings.value(
                "/infra3d_viewer/general/layer_group", DEFAULT_LAYER_GROUP
            )
        )
        self.lineEdit_currentPositionLayer.setText(
            self.settings.value(
                "/infra3d_viewer/general/current_position_layer",
                self.default_current_position_layer,
            )
        )
        self.lineEdit_networkLayerLines.setText(
            self.settings.value(
                "/infra3d_viewer/general/network_layer_name_lines",
                self.default_network_layer_lines,
            )
        )
        self.lineEdit_networkLayerHexes.setText(
            self.settings.value(
                "/infra3d_viewer/general/network_layer_name_hexes",
                self.default_network_layer_hexes,
            )
        )

        stored_rules = self.settings.value(
            "/infra3d_viewer/advanced/loa_rules", DEFAULT_LOA_RULES
        )
        self.loaRules = [
            LoaRule(r["type"], r["level"], r["min"], r["max"]) for r in stored_rules
        ]

    def save_settings(self):
        if self.spinBox_serverPort.value() != int(
            self.settings.value(
                "/infra3d_viewer/general/server_port", DEFAULT_SERVER_PORT
            )
        ):
            QMessageBox.warning(
                None,  # type: ignore
                self.tr("Infra3D: Server port changed"),
                self.tr("Restart QGIS for the port change to take effect!"),
            )

        # Infra3D credentials
        self.settings.setValue(
            "/infra3d_viewer/general/tenant_identifier",
            self.lineEdit_tenantIdentifier.text(),
        )
        self.settings.setValue(
            "/infra3d_viewer/general/start_project_uid",
            self.lineEdit_startProjectUID.text(),
        )
        # SocketIO server
        self.settings.setValue(
            "/infra3d_viewer/general/server_port", self.spinBox_serverPort.value()
        )

        self.settings.setValue(
            "/infra3d_viewer/general/layer_group", self.lineEdit_layerGroup.text()
        )
        self.settings.setValue(
            "/infra3d_viewer/general/current_position_layer",
            self.lineEdit_currentPositionLayer.text(),
        )
        self.settings.setValue(
            "/infra3d_viewer/general/network_layer_name_lines",
            self.lineEdit_networkLayerLines.text(),
        )
        self.settings.setValue(
            "/infra3d_viewer/general/network_layer_name_hexes",
            self.lineEdit_networkLayerHexes.text(),
        )

        self.settings.setValue(
            "/infra3d_viewer/advanced/loa_rules",
            [
                {
                    "type": r.type,
                    "level": r.level,
                    "min": r.minScale,
                    "max": r.maxScale,
                }
                for r in self.loaModel.rules
            ],
        )

    def add_loa_rule(self):
        row = self.loaModel.rowCount()
        self.loaModel.beginInsertRows(QModelIndex(), row, row)
        self.loaModel.rules.append(LoaRule("routeLines", 0, 0, 0))
        self.loaModel.endInsertRows()

    def remove_loa_rule(self):
        index = self.tableView_loaRules.currentIndex()
        if not index.isValid():
            return

        row = index.row()
        self.loaModel.beginRemoveRows(QModelIndex(), row, row)
        del self.loaModel.rules[row]
        self.loaModel.endRemoveRows()

    def reset_page(self):
        if self.tabWidget.currentIndex() == 0:
            self.lineEdit_tenantIdentifier.setText("")
            self.settings.setValue("/infra3d_viewer/general/tenant_identifier", "")
            self.lineEdit_startProjectUID.setText("")
            self.settings.setValue("/infra3d_viewer/general/start_project_uid", "")
            self.spinBox_serverPort.setValue(DEFAULT_SERVER_PORT)
            self.settings.setValue(
                "/infra3d_viewer/general/server_port", DEFAULT_SERVER_PORT
            )
            self.lineEdit_layerGroup.setText(DEFAULT_LAYER_GROUP)
            self.settings.setValue(
                "/infra3d_viewer/general/layer_group", DEFAULT_LAYER_GROUP
            )
            self.lineEdit_currentPositionLayer.setText(
                self.default_current_position_layer
            )
            self.settings.setValue(
                "/infra3d_viewer/general/current_position_layer",
                self.default_current_position_layer,
            )
            self.lineEdit_networkLayerLines.setText(self.default_network_layer_lines)
            self.settings.setValue(
                "/infra3d_viewer/general/network_layer_name_lines",
                self.default_network_layer_lines,
            )
            self.lineEdit_networkLayerHexes.setText(self.default_network_layer_hexes)
            self.settings.setValue(
                "/infra3d_viewer/general/network_layer_name_hexes",
                self.default_network_layer_hexes,
            )
        elif self.tabWidget.currentIndex() == 1:
            self.loaRules = [
                LoaRule(r["type"], r["level"], r["min"], r["max"])
                for r in DEFAULT_LOA_RULES
            ]
            self.settings.setValue(
                "/infra3d_viewer/advanced/loa_rules", DEFAULT_LOA_RULES
            )
            self.loaModel.beginResetModel()
            self.loaModel.rules = self.loaRules
            self.loaModel.endResetModel()
        else:
            self.iface.messageBar().pushMessage(
                "infra3D",
                "Page not reseted: Unknown page {}".format(
                    self.tabWidget.currentIndex()
                ),
                Qgis.MessageLevel.Critical,
                5,
            )
