# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Infra3dClient
                                 A QGIS plugin
 This plugin is an integration of the Infra3D application with QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-09-28
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Sourcepole AG
        email                : hka@sourcepole.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

# -*- coding: utf-8 -*-

import uuid

from qgis.PyQt.QtCore import pyqtSignal, QObject, QCoreApplication
from qgis.PyQt.QtWidgets import QMessageBox


class Infra3dClient(QObject):
    """This is a convenience class that should ease the access
    to the infra3D application, that is running in the browser.
    """

    webapp_loaded = pyqtSignal(dict)
    webapp_initialized = pyqtSignal(dict)
    position_changed = pyqtSignal(dict)
    azimuth_changed = pyqtSignal(dict)
    connection_failed = pyqtSignal(dict)
    network_received = pyqtSignal(dict)

    def __init__(self, local_server):
        super(Infra3dClient, self).__init__()
        self.local_server = local_server
        self._connected = False
        self._signal_connected = False

    def connect(self) -> bool:
        """Try to connect to the local server and subscribe to browser events."""
        if self._connected is True:
            return True

        if self.local_server.running is False or not self.local_server.websocket_address():
            QMessageBox.critical(
                None,  # type: ignore
                QCoreApplication.translate("infra3D", "Connection error"),
                QCoreApplication.translate(
                    "infra3D", "Could not connect to the local websocket bridge!"
                ),
            )
            self.connection_failed.emit({})
            return False

        if self._signal_connected is False:
            self.local_server.websocket_message_received.connect(
                self._handle_websocket_message
            )
            self._signal_connected = True

        self._connected = True
        return True

    def init(self, tenant_identifier: str = "", start_project_uid: str = ""):
        self.__call_remote_method(
            "initInfra3d",
            {
                "tenantIdentifier": tenant_identifier,
                "startProjectUid": start_project_uid,
            },
        )

    def setOnPositionChanged(self):
        self.connect()

    def getNetwork(
        self,
        level: str,
        loa: int,
        minEasting: float,
        maxEasting: float,
        minNorthing: float,
        maxNorthing: float,
        epsg: int,
    ) -> None:
        self.__call_remote_method(
            "getNetwork",
            {
                "level": level,
                "loa": loa,
                "minEasting": minEasting,
                "maxEasting": maxEasting,
                "minNorthing": minNorthing,
                "maxNorthing": maxNorthing,
                "epsg": epsg,
            },
        )

    def moveTo2DPosition(self, easting: float, northing: float):
        self.__call_remote_method(
            "moveTo2DPosition", {"easting": easting, "northing": northing}
        )

    def __call_remote_method(self, method_name: str, args: dict):
        self.connect()
        request = {"id": str(uuid.uuid1()), "method": method_name, "args": args}

        try:
            self.local_server.send_websocket_message(request)
        except Exception:
            pass

    def disconnect(self):
        self._connected = False
        if self._signal_connected:
            try:
                self.local_server.websocket_message_received.disconnect(
                    self._handle_websocket_message
                )
            except (TypeError, RuntimeError):
                pass
            self._signal_connected = False

    def _handle_websocket_message(self, payload: dict):
        event_name = payload.get("event")
        params = payload.get("params", {})

        if event_name == "loaded":
            self.webapp_loaded.emit(params)
        elif event_name == "initialized":
            self.webapp_initialized.emit(params)
        elif event_name == "positionChanged":
            self.position_changed.emit(params)
        elif event_name == "azimuthChanged":
            self.azimuth_changed.emit(params)
        elif event_name == "newNetwork":
            self.network_received.emit(params)
        elif event_name == "rpcresponse":
            pass
