# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Infra3d
                                 A QGIS plugin
 This plugin is an integration of the Infra3D application with QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-09-28
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Sourcepole AG
        email                : hka@sourcepole.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from threading import Thread
import os.path
import time
from pyproj import Transformer
import json
import math

from qgis.gui import QgisInterface, QgsMapToolPan
from qgis.core import Qgis, QgsPointXY, QgsRectangle
from qgis.PyQt.QtCore import (
    QEventLoop,
    QSettings,
    QTranslator,
    QCoreApplication,
    QUrl,
    QDir,
    Qt,
)
from qgis.PyQt.QtGui import QIcon, QDesktopServices, QGuiApplication
from qgis.PyQt.QtWidgets import QAction, QMessageBox

from .infra3d_settings_dialog import (
    Infra3DSettingsDialog,
)
from .infra3d_settings import Infra3dSettings
from .infra3d_client import Infra3dClient
from .infra3d_map_tool import Infra3dMapTool
from .infra3d_layer_utils import Infra3DLayerUtils
from .server.local_server import LocalServer


class Infra3d:
    """QGIS Plugin Implementation."""

    def __init__(self, iface: QgisInterface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.join(os.path.dirname(__file__), "..")

        # Init the icons path
        QDir.addSearchPath(
            "icons", os.path.join(os.path.dirname(__file__), "resources")
        )

        # initialize locale
        locale = QSettings().value("locale/userLocale", "en")[0:2]
        locale_path = os.path.join(
            self.plugin_dir, "i18n", "infra3d_{}.qm".format(locale)
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.toolbar = self.iface.addToolBar("infra3D")
        self.toolbar.setObjectName("infra3D")
        self.settings = Infra3dSettings()

        # Prepare local HTTP server
        self.local_server = LocalServer()
        app = QCoreApplication.instance()
        if app is not None:
            app.aboutToQuit.connect(self.local_server.stop)

        # Initialize Infra3D client
        self.infra3d_client = Infra3dClient(self.local_server)

        # Initialize map tool
        self.infra3d_map_tool = Infra3dMapTool(
            self.iface,
            self.infra3d_client,
            self.start_infra3d_blocking,
        )

        self.panTool = QgsMapToolPan(self.iface.mapCanvas())

        self.layer_utils = Infra3DLayerUtils(self.iface, self.settings)

        self.first_position_received = False

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        # Ownership of a QAction is not transfered to QMenu, so we need to keep
        # the references of the actions alive. The easiest way is with an actions list.

        # Start infra3D action
        self.start_infra3d_action = QAction(
            QIcon("icons:infra3d.svg"),
            QCoreApplication.translate("infra3D", "Enable infra3D"),
            self.iface.mainWindow(),
        )
        self.start_infra3d_action.toggled.connect(self.start_infra3d)
        self.start_infra3d_action.setCheckable(True)
        self.actions.append(self.start_infra3d_action)

        # Set infra3D position action
        self.set_infra3d_position_action = QAction(
            QIcon("icons:infra3d_pin.svg"),
            QCoreApplication.translate("infra3D", "Set infra3D position"),
            self.iface.mainWindow(),
        )
        self.set_infra3d_position_action.triggered.connect(self.set_infra3d_position)
        self.set_infra3d_position_action.setEnabled(False)
        self.set_infra3d_position_action.setCheckable(True)
        self.infra3d_map_tool.setAction(self.set_infra3d_position_action)
        self.actions.append(self.set_infra3d_position_action)

        # Zoom to marker action
        self.zoom_to_marker_action = QAction(
            QIcon("icons:infra3d_zoom.svg"),
            QCoreApplication.translate("infra3D", "Zoom to marker"),
            self.iface.mainWindow(),
        )
        self.zoom_to_marker_action.setEnabled(False)
        self.zoom_to_marker_action.triggered.connect(self.zoom_to_marker)
        self.actions.append(self.zoom_to_marker_action)

        self.infra3d_settings = Infra3DSettingsDialog(
            self.iface.mainWindow(), self.iface, self.settings
        )
        self.show_settings_action = QAction(
            QIcon(":/images/themes/default/mActionOptions.svg"),
            QCoreApplication.translate("infra3D", "Settings"),
            self.iface.mainWindow(),
        )
        self.show_settings_action.triggered.connect(self.infra3d_settings.show)
        self.show_settings_action.setCheckable(False)
        self.actions.append(self.show_settings_action)

        for action in self.actions:
            self.toolbar.addAction(action)

    def onExtentsChanged(self) -> None:
        """
        Fired whenever the extent of the QGIS mapCanvas changes.
        """
        try:
            extent = self.iface.mapCanvas().extent().toString()

            # If QGIS is started, the extent is "Null" -.-
            if not extent or extent == "Null":
                return

            ll, ur = extent.split(" : ")
            minEasting, minNorthing = [float(i) for i in ll.split(",")]
            maxEasting, maxNorthing = [float(i) for i in ur.split(",")]
            epsg = self.iface.mapCanvas().mapSettings().destinationCrs().authid()
            epsg_number = epsg.split(":")[1] if ":" in epsg else epsg

            scale = self.iface.mapCanvas().scale()
            loa_rules = self.settings.loa_rules

            if loa_rules is not None:
                loa_rule = next(
                    (r for r in loa_rules if r["min"] <= scale < r["max"]),
                    None,
                )
                if loa_rule is not None:
                    self.infra3d_client.getNetwork(
                        loa_rule["type"],
                        loa_rule["level"],
                        minEasting,
                        maxEasting,
                        minNorthing,
                        maxNorthing,
                        int(epsg_number),
                    )
        except Exception as e:
            self.iface.messageBar().pushMessage(
                "infra3D",
                QCoreApplication.translate(
                    "infra3D", "Error while synchronizing network: "
                )
                + str(e),
                Qgis.MessageLevel.Warning,
                5,
            )

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        self.infra3d_client.disconnect()
        self.local_server.stop()

        for action in self.actions:
            self.iface.removePluginWebMenu("infra3D", action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    def _show_local_server_startup_error(self, message: str):
        QMessageBox.critical(
            self.iface.mainWindow(),
            QCoreApplication.translate("infra3D", "infra3D server error"),
            message,
        )

    def _safe_disconnect(self, signal, slot):
        try:
            signal.disconnect(slot)
        except (TypeError, RuntimeError):
            pass

    def start_infra3d(self, checked: bool):
        """
        Starts/ends the webserver.

        Parameters
        ----------
        checked : bool
            enable/disable
        """
        if checked:
            if self.local_server.running is False:
                self.start_local_server()

            if self.wait_for_local_server() is False:
                self.show_settings_action.setEnabled(True)
                self.start_infra3d_action.setChecked(False)
                return

            self.connect()

            self.open_browser()

            self.show_settings_action.setEnabled(False)

            self.layer_utils.add_layers()

        else:
            self.disconnect()
            
            self.local_server.stop()

            self.iface.mapCanvas().setMapTool(self.panTool)

            self.set_infra3d_position_action.setEnabled(False)
            self.zoom_to_marker_action.setEnabled(False)
            self.show_settings_action.setEnabled(True)

            self.layer_utils.remove_layers()

    def start_infra3d_blocking(self):
        """
        Blocks infra3d
        """
        if not self.start_infra3d_action.isChecked():
            # Wait until started
            QGuiApplication.setOverrideCursor(Qt.CursorShape.WaitCursor)
            blockingWait = QEventLoop()
            self.infra3d_client.webapp_initialized.connect(blockingWait.quit)
            self.infra3d_client.connection_failed.connect(blockingWait.quit)
            self.start_infra3d_action.toggle()
            blockingWait.exec_()
            QGuiApplication.restoreOverrideCursor()

    def set_infra3d_position(self, checked: bool):
        """
        Update the projection of the QGIS mapCanvas and enable/disable the position picker to define the position the viewer is supposed to jump to.

        Parameters
        ----------
        checked : bool
            Enable/disable
        """
        if checked:
            self.iface.mapCanvas().setMapTool(self.infra3d_map_tool)
        else:
            self.iface.mapCanvas().setMapTool(self.panTool)

    def check_settings(self) -> bool:
        """Check whether the settings are configured properly.

        Returns:
            bool: Return True if the settings are defined,
            otherwise returns False
        """

        missing_configurations = []

        if len(missing_configurations) > 0:
            self.iface.messageBar().pushMessage(
                "infra3D",
                QCoreApplication.translate(
                    "infra3D", "The following settings are not set: "
                )
                + ", ".join(missing_configurations),
                Qgis.MessageLevel.Critical,  # type: ignore
                5,
            )
            return False

        return True

    def open_browser(self):
        """Start / open a browser / browser tab and initialize the
        infra3D application via the `init` function.
        """

        # Don't do anything if the local server is not running
        if self.local_server.running is False:
            QGuiApplication.restoreOverrideCursor()
            self.iface.messageBar().pushMessage(
                "infra3D",
                QCoreApplication.translate(
                    "infra3D",
                    "infra3D server did not start correctly. Please restart QGIS",
                ),
                Qgis.MessageLevel.Critical,  # type: ignore
                5,
            )
            return

        # Check if settings are set correctly
        if self.check_settings() is False:
            QGuiApplication.restoreOverrideCursor()
            self.start_infra3d_action.setChecked(False)
            return

        # If we cannot connect to the server, then there is
        # no need to start the browser
        if not self.infra3d_client.connect():
            QGuiApplication.restoreOverrideCursor()
            return

        # Start browser
        QDesktopServices.openUrl(QUrl(self.local_server_address()))

    def connect(self):
        """Connect the signals of the infra3D client with the respective slots
        in this plugin.
        """
        self.infra3d_client.webapp_loaded.connect(self._on_webapp_loaded)
        self.infra3d_client.network_received.connect(self._on_network_received)
        self.infra3d_client.webapp_initialized.connect(self._on_webapp_initialized)
        self.infra3d_client.position_changed.connect(self.update_marker_position)
        self.infra3d_client.azimuth_changed.connect(self.update_marker_orientation)

        self.iface.mapCanvas().extentsChanged.connect(self.onExtentsChanged)

    def disconnect(self):
        """Disconnect the signals of the infra3D client with the respective slots
        in this plugin.
        """
        self._safe_disconnect(self.infra3d_client.webapp_loaded, self._on_webapp_loaded)
        self._safe_disconnect(self.infra3d_client.network_received, self._on_network_received)
        self._safe_disconnect(self.infra3d_client.webapp_initialized, self._on_webapp_initialized)
        self._safe_disconnect(self.infra3d_client.position_changed, self.update_marker_position)
        self._safe_disconnect(self.infra3d_client.azimuth_changed, self.update_marker_orientation)

        self._safe_disconnect(self.iface.mapCanvas().extentsChanged, self.onExtentsChanged)

    def _on_webapp_initialized(self):
        """
        This function is called when the `webapp_initialized` signal is emitted.
        """

        self.first_position_received = False

        QGuiApplication.restoreOverrideCursor()
        self.infra3d_client.setOnPositionChanged()
        self.set_infra3d_position_action.setEnabled(True)
        self.zoom_to_marker_action.setEnabled(True)

    def _on_network_received(self, network: dict):
        """
        This function is called when the `network_received` signal is emitted.
        """
        self.show_network(network)

    def _on_webapp_loaded(self):
        """
        This function is called when the `webapp_loaded` signal is emitted.
        """
        self.infra3d_client.init(
            self.settings.tenant_identifier, self.settings.start_project_uid
        )

    def show_network(self, network: json) -> None:
        routes = network.get("routes")
        if not routes or not routes.get("features"):
            return

        geom_type = routes["features"][0]["geometry"]["type"]

        self.layer_utils.update_network_layer(routes, geom_type)

    def update_marker_position(self, node: dict):
        """Place the marker `self.infra3d_marker` on the map canvas and
        set the orientation.

        Args:
            node (dict): Dictionary containing the node information
        """
        point = QgsPointXY(node["longitude"], node["latitude"])

        self.layer_utils.update_marker(position=point)

        if self.first_position_received is False:
            self.zoom_to_marker()
            self.first_position_received = True

    def update_marker_orientation(self, azi: dict):
        """Update the orientation of the marker `self.infra3d_marker`.

        Args:
            orientation (float): Marker orientation
        """
        self.layer_utils.update_marker(azimuth=azi["azimuth"])

    def zoom_to_marker(self):
        """Zoom to the current position of the marker on the map
        and refresh the map canvas
        """

        zoom_level = 18
        resolution = 40075016.686 / (2 ** (zoom_level + 8))
        buffer = resolution * self.iface.mapCanvas().width() / 2  # in m

        earth_radius = 6378137.0
        buffer_y = (buffer / earth_radius) * (180.0 / math.pi)
        buffer_x = buffer_y / max(math.cos(math.radians(self.layer_utils.marker_position.y())), 1e-12)

        bl_point = QgsPointXY(
            self.layer_utils.marker_position.x() - buffer_x,
            self.layer_utils.marker_position.y() - buffer_y
        )
        tr_point = QgsPointXY(
            self.layer_utils.marker_position.x() + buffer_x,
            self.layer_utils.marker_position.y() + buffer_y
        )

        # Calculate the zoom window in map units first so it works for any CRS.
        epsg = self.iface.mapCanvas().mapSettings().destinationCrs().authid()
        point_transformer = Transformer.from_crs("EPSG:4326", epsg, always_xy=True)

        transformed_bl_point = point_transformer.transform(bl_point.x(), bl_point.y())
        transformed_tr_point = point_transformer.transform(tr_point.x(), tr_point.y())


        self.iface.mapCanvas().setExtent(
            QgsRectangle(
                transformed_bl_point[0] - buffer_x,
                transformed_bl_point[1] - buffer_y,
                transformed_tr_point[0] + buffer_x,
                transformed_tr_point[1] + buffer_y,
            ),
            True
        )
        self.iface.mapCanvas().refresh()

    def start_local_server(self):
        """Start the local server in a different thread
        so we don't block the QGIS application.
        """

        def start_server():
            self.local_server.start()

        self.local_server_thread = Thread(target=start_server, daemon=True)
        self.local_server_thread.start()

    def wait_for_local_server(self, timeout: float = 5.0) -> bool:
        """Wait until the local server has bound its port."""
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if self.local_server.started.is_set() and self.local_server.running:
                return True
            if self.local_server.started.is_set() and self.local_server.startup_error is not None:
                break
            time.sleep(0.05)

        error_message = getattr(self.local_server, "startup_error_message", None)
        if error_message:
            self._show_local_server_startup_error(
                QCoreApplication.translate("infra3D", error_message)
            )
            return False

        self._show_local_server_startup_error(
            QCoreApplication.translate(
                "infra3D",
                "infra3D server did not start correctly. Please restart QGIS",
            )
        )
        return False

    def local_server_address(self) -> str:
        """Build the local server address

        Returns:
            str: Server address
        """
        return self.local_server.server_address()
