# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Infra3DSettings
                                 A QGIS plugin
 This plugin is an integration of the Infra3D application with QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-09-28
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Sourcepole AG
        email                : hka@sourcepole.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from .infra3d_settings import Infra3dSettings

from .infra3d_settings_loarule import LoaRule, LoaRuleTableModel
from qgis.core import Qgis, QgsApplication
from qgis.PyQt import uic
from qgis.PyQt.QtWidgets import QMainWindow, QDialog, QDialogButtonBox
from qgis.PyQt.QtCore import (
    QModelIndex,
    Qt,
    QSortFilterProxyModel,
    QCoreApplication,
)

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "ui/settings.ui")
)


class Infra3DSettingsDialog(QDialog, FORM_CLASS):
    def __init__(self, parent: QMainWindow, iface, settings: Infra3dSettings):
        super(Infra3DSettingsDialog, self).__init__(parent)

        self.setupUi(self)
        self.iface = iface
        self.settings = settings

        # Get values from settings and prefill dialog
        self.prefill_from_settings()

        self.loaModel = LoaRuleTableModel(self.loaRules, self)
        self.tableView_loaRules.setModel(self.loaModel)

        self.loaProxyModel = QSortFilterProxyModel(self)
        self.loaProxyModel.setSourceModel(self.loaModel)

        # IMPORTANT: enable correct numeric sorting
        self.loaProxyModel.setSortRole(Qt.ItemDataRole.DisplayRole)
        self.loaProxyModel.setDynamicSortFilter(True)

        self.tableView_loaRules.setModel(self.loaProxyModel)
        self.tableView_loaRules.setSortingEnabled(True)

        # Set default sorting to ascending by min scale
        self.tableView_loaRules.sortByColumn(2, Qt.SortOrder.AscendingOrder)

        self.pushButton_addLoaRule.setIcon(
            QgsApplication.getThemeIcon("symbologyAdd.svg")
        )
        self.pushButton_removeLoaRule.setIcon(
            QgsApplication.getThemeIcon("symbologyRemove.svg")
        )
        self.pushButton_addLoaRule.clicked.connect(self.add_loa_rule)
        self.pushButton_removeLoaRule.clicked.connect(self.remove_loa_rule)

        self.pushButton_resetPage.clicked.connect(self.reset_page)
        self.buttonBox.button(QDialogButtonBox.StandardButton.Save).clicked.connect(
            self.save_settings
        )
        self.buttonBox.button(QDialogButtonBox.StandardButton.Cancel).clicked.connect(
            self.prefill_from_settings
        )

    def prefill_from_settings(self):
        """Fill lineedits in the settings dialog with values from QSettings or
        just use default values
        """
        # Infra3D credentials
        self.lineEdit_tenantIdentifier.setText(self.settings.tenant_identifier)
        self.lineEdit_startProjectUID.setText(self.settings.start_project_uid)

        self.lineEdit_layerGroup.setText(self.settings.layer_group)
        self.lineEdit_currentPositionLayer.setText(self.settings.current_position_layer)
        self.lineEdit_networkLayerLines.setText(self.settings.network_layer_name_lines)
        self.lineEdit_networkLayerHexes.setText(self.settings.network_layer_name_hexes)

        stored_rules = self.settings.loa_rules
        self.loaRules = [
            LoaRule(r["type"], r["level"], r["min"], r["max"]) for r in stored_rules
        ]

    def save_settings(self):
        # Infra3D credentials
        self.settings.tenant_identifier = self.lineEdit_tenantIdentifier.text()
        self.settings.start_project_uid = self.lineEdit_startProjectUID.text()

        self.settings.layer_group = self.lineEdit_layerGroup.text()
        self.settings.current_position_layer = self.lineEdit_currentPositionLayer.text()
        self.settings.network_layer_name_lines = self.lineEdit_networkLayerLines.text()
        self.settings.network_layer_name_hexes = self.lineEdit_networkLayerHexes.text()

        self.settings.loa_rules = [
            {
                "type": r.type,
                "level": r.level,
                "min": r.minScale,
                "max": r.maxScale,
            }
            for r in self.loaModel.rules
        ]

        self.settings.save()

    def add_loa_rule(self):
        row = self.loaModel.rowCount()
        self.loaModel.beginInsertRows(QModelIndex(), row, row)
        self.loaModel.rules.append(LoaRule("routeLines", 0, 0, 0))
        self.loaModel.endInsertRows()

    def remove_loa_rule(self):
        index = self.tableView_loaRules.currentIndex()
        if not index.isValid():
            return

        row = index.row()
        self.loaModel.beginRemoveRows(QModelIndex(), row, row)
        del self.loaModel.rules[row]
        self.loaModel.endRemoveRows()

    def reset_page(self):
        if self.tabWidget.currentIndex() == 0:
            self.settings.reset_to_defaults("general")

            self.lineEdit_tenantIdentifier.setText(self.settings.tenant_identifier)
            self.lineEdit_startProjectUID.setText(self.settings.start_project_uid)
            self.lineEdit_layerGroup.setText(self.settings.layer_group)
            self.lineEdit_currentPositionLayer.setText(
                self.settings.current_position_layer
            )
            self.lineEdit_networkLayerLines.setText(
                self.settings.network_layer_name_lines
            )
            self.lineEdit_networkLayerHexes.setText(
                self.settings.network_layer_name_hexes
            )
        elif self.tabWidget.currentIndex() == 1:
            self.settings.reset_to_defaults("advanced")

            self.loaRules = [
                LoaRule(r["type"], r["level"], r["min"], r["max"])
                for r in self.settings.loa_rules
            ]
            self.loaModel.beginResetModel()
            self.loaModel.rules = self.loaRules
            self.loaModel.endResetModel()
        else:
            self.iface.messageBar().pushMessage(
                "infra3D",
                QCoreApplication.translate("infra3D", "Page not reseted: Unknown page ")
                + str(self.tabWidget.currentIndex()),
                Qgis.MessageLevel.Critical,
                5,
            )
