name: Package infra3D plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: |
          mkdir Infra3DPlugin
          rsync -av --exclude='__pycache__/' --exclude='*.pyc' i18n src __init__.py metadata.txt LICENSE CHANGELOG.md README.md Infra3DPlugin/
          zip -r Infra3DPlugin.zip Infra3DPlugin/

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: Infra3DPlugin.zip
